CEOS-Developers/CEOS-BE

build.gradle, src/main/java/ceos/backend/global/config/WebSecurityConfig.java, src/main/java/ceos/backend/global/config/jwt/JwtAccessDeniedHandler.java, src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationEntryPoint.java, src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationFilter.java, src/main/java/ceos/backend/global/config/jwt/JwtExceptionHandlerFilter.java, src/main/java/ceos/backend/global/config/jwt/TokenProvider.java, src/main/java/ceos/backend/global/config/user/CustomUserDetails.java, src/main/java/ceos/backend/global/config/user/CustomUserDetailsService.java, src/main/java/ceos/backend/global/error/GlobalErrorCode.java, src/main/java/ceos/backend/global/error/exception/TokenValidateException.java
---
Filter 작성을 통해서 WebSecurity 설정을 하였습니다.
그 외 토큰 관련 함수와 ErrorCode, Exception을 작성하였습니다.
DB 연결 및 도메인 작성이 완료되면 해당 코드 추가할 예정입니다.
<br><br><br>
토큰 관련 에러는 일단 제 임의대로 작성해두었는데 추후 필요한 에러만 남기고 정리할 예정입니다.
<br><br>
---
feat/security
---
- close #4
=> [feat] Security 설정

.gitignore, src/main/java/ceos/backend/global/config/WebSecurityConfig.java, src/main/java/ceos/backend/global/config/jwt/JwtAccessDeniedHandler.java, src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationEntryPoint.java, src/main/java/ceos/backend/global/config/jwt/TokenProvider.java, src/main/java/ceos/backend/global/error/exception/NoTokenException.java, src/main/resources/application.yml
---
security 변수 관리를 위해서 application.yml 파일을 둘로 분리했습니다. 
<br><br><br>
application.yml에는 위와 같이 작성하고 application-secret.yml에 변수 작성해주시면 됩니다.
<br><br><br>
그 외 겸사겸사 exception을 추가하고 Handler에 적용했습니다.
빠뜨린 어노테이션 추가 및 코드 순서 변경을 통해 사소한 에러를 해결했습니다.
---
feat/security
---
이슈 번호
- close #4
=> [feat] Spring Security 변수 관리 및 에러 적용

build.gradle, src/main/java/ceos/backend/BackendApplication.java, src/main/java/ceos/backend/domain/example/ExampleController.java, src/main/java/ceos/backend/domain/example/dto/SlackTest.java, src/main/java/ceos/backend/global/common/dto/SlackErrorMessage.java, src/main/java/ceos/backend/global/common/event/Event.java, src/main/java/ceos/backend/global/common/event/EventConfig.java, src/main/java/ceos/backend/global/common/filter/MultiReadInputStream.java, src/main/java/ceos/backend/global/common/filter/MultiReadInputStreamFilter.java, src/main/java/ceos/backend/global/common/helper/SpringEnvironmentHelper.java, src/main/java/ceos/backend/global/common/response/ResponseAdvicer.java, src/main/java/ceos/backend/global/error/GlobalExceptionHandler.java, src/main/java/ceos/backend/infra/slack/SlackHelper.java, src/main/java/ceos/backend/infra/slack/SlackMessageGenerater.java, src/main/java/ceos/backend/infra/slack/SlackSendMessageHandler.java, src/main/resources/application.yml
---
에러 발생시 슬랙으로 알림이 오는 기능 구현했습니다.
비동기 처리 추가했습니다.
input stream 캐싱할 수 있도록 필터 추가했습니다.
-> ContentCachingRequestWrapper 사용 안해도 됩니다.
---
feat/slack
---
이슈 번호
- close #9
=> [feat] 에러 slack 알림 구현

src/main/java/ceos/backend/domain/application/domain/Application.java
---
Application 의 bool otDate -> **LocalDate otDate** 로, bool demodayDate -> **LocalDate demodayDate** 로 수정
---
feat/domain
---
- close #23
=> [feat] otDate, demodayDate 필드 수정

src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
CORS 설정을 위해 도메인을 설정에 추가해주었습니다.
---
feat/security
---
이슈 번호
- close #
=> [add] CORS 추가

src/main/java/ceos/backend/domain/admin/AdminController.java, src/main/java/ceos/backend/domain/admin/domain/Admin.java, src/main/java/ceos/backend/domain/admin/domain/AdminRole.java, src/main/java/ceos/backend/domain/admin/dto/request/GrantAuthorityRequest.java, src/main/java/ceos/backend/domain/admin/dto/response/GetAdminsResponse.java, src/main/java/ceos/backend/domain/admin/exception/AdminErrorCode.java, src/main/java/ceos/backend/domain/admin/exception/InvalidAction.java, src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java, src/main/java/ceos/backend/domain/admin/repository/AdminMapper.java, src/main/java/ceos/backend/domain/admin/repository/AdminRepository.java, src/main/java/ceos/backend/domain/admin/service/AdminService.java, src/main/java/ceos/backend/domain/admin/vo/AdminBriefInfoVo.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java, src/main/java/ceos/backend/global/config/jwt/JwtAccessDeniedHandler.java, src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationEntryPoint.java, src/main/java/ceos/backend/global/config/user/AdminDetails.java, src/main/java/ceos/backend/global/config/user/AdminDetailsService.java, src/main/java/ceos/backend/global/error/GlobalErrorCode.java, src/main/java/ceos/backend/global/error/exception/ForbiddenAdminException.java
---
관리자 기능을 구현했습니다.
- 어드민 목록 제공
- 어드민 권한 변경
- 어드민 삭제
SuperAdmin은 자기 자신에 대한 작업은 수행할 수 없습니다.<br>
그 외 권한이 필요한 URL 패턴을  Security에 정의했습니다. API 업데이트 될 때마다 배열에 추가해주시면 됩니다.
---
feat/admin
---
이슈 번호
- close #52
=> [feat] 관리자 기능 구현

src/main/java/ceos/backend/domain/project/ProjectController.java, src/main/java/ceos/backend/domain/project/domain/Participant.java, src/main/java/ceos/backend/domain/project/domain/Project.java, src/main/java/ceos/backend/domain/project/domain/ProjectImage.java, src/main/java/ceos/backend/domain/project/domain/ProjectUrl.java, src/main/java/ceos/backend/domain/project/domain/ProjectUrlCategory.java, src/main/java/ceos/backend/domain/project/dto/request/CreateProjectRequest.java, src/main/java/ceos/backend/domain/project/dto/request/ProjectRequest.java, src/main/java/ceos/backend/domain/project/dto/response/GetProjectResponse.java, src/main/java/ceos/backend/domain/project/dto/response/GetProjectsResponse.java, src/main/java/ceos/backend/domain/project/exception/DataNotFound.java, src/main/java/ceos/backend/domain/project/exception/DuplicateProject.java, src/main/java/ceos/backend/domain/project/exception/InvalidData.java, src/main/java/ceos/backend/domain/project/exception/ProjectErrorCode.java, src/main/java/ceos/backend/domain/project/exception/ProjectNotFound.java, src/main/java/ceos/backend/domain/project/helper/ProjectHelper.java, src/main/java/ceos/backend/domain/project/repository/ParticipantRepository.java, src/main/java/ceos/backend/domain/project/repository/ProjectImageRepository.java, src/main/java/ceos/backend/domain/project/repository/ProjectMapper.java, src/main/java/ceos/backend/domain/project/repository/ProjectRepository.java, src/main/java/ceos/backend/domain/project/repository/ProjectUrlRepository.java, src/main/java/ceos/backend/domain/project/service/ProjectService.java, src/main/java/ceos/backend/domain/project/vo/ParticipantVo.java, src/main/java/ceos/backend/domain/project/vo/ProjectBriefInfoVo.java, src/main/java/ceos/backend/domain/project/vo/ProjectImageVo.java, src/main/java/ceos/backend/domain/project/vo/ProjectInfoVo.java, src/main/java/ceos/backend/domain/project/vo/ProjectUrlVo.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
프로젝트 생성, 수정, 삭제, 읽기 API를 작성하였습니다.
- 프로젝트에 각 카테고리별로 url은 하나씩만 입력 가능합니다. (ex. 깃허브, 비핸스 각 하나씩)
- 프로젝트에 각 카테고리별로 image는 꼭 하나씩 입력되어야 합니다.
---
feat/project
---
이슈 번호
- close #55
=> [feat] 프로젝트 관리 기능 구현

src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
Swagger Patterns 을 수정하였습니다
---
fix/swagger
---
이슈 번호
- close #
=> [fix] Swagger Patterns 수정

.github/workflows/deploy.yml, src/main/java/ceos/backend/global/config/OpenApiConfig.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
Swagger 에서 Execute 시 발생하는 오류를 해결했습니다
Server url 을 노출시키지 않도록 수정했습니다 (WebSecurityConfig, OpenApiConfig)
---
fix/swagger
---
이슈 번호
- close #60
=> [fix] Swagger 오류

src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java, src/main/java/ceos/backend/domain/recruitment/dto/request/UpdateRecruitmentRequest.java, src/main/java/ceos/backend/domain/recruitment/dto/response/GetRecruitmentResponse.java, src/main/java/ceos/backend/domain/recruitment/service/RecruitmentService.java
---
prod_img., dev_img, design_img DB(recruitment 테이블)에서 column 제거,
get response에 openchat_url 추가
---
chore/recruitments
---
이슈 번호
- close #
=> [chore] recruitments api 수정

src/main/java/ceos/backend/domain/application/dto/response/GetApplicationQuestion.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/vo/InterviewDateTimesVo.java
---
지원서 질문 보기 api response 변경
---
---
이슈 번호
- close #73
=> [refac] 지원서 질문 보기 api response 변경

.gitignore, build.gradle, docker-compose.yml, src/main/java/ceos/backend/domain/admin/AdminController.java, src/main/java/ceos/backend/domain/admin/dto/request/RefreshTokenRequest.java, src/main/java/ceos/backend/domain/admin/dto/response/TokenResponse.java, src/main/java/ceos/backend/domain/admin/exception/AdminErrorCode.java, src/main/java/ceos/backend/domain/admin/exception/NotRefreshToken.java, src/main/java/ceos/backend/domain/admin/exception/RefreshTokenNotFound.java, src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java, src/main/java/ceos/backend/domain/admin/repository/AdminMapper.java, src/main/java/ceos/backend/domain/admin/service/AdminService.java, src/main/java/ceos/backend/global/config/RedisConfig.java, src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationFilter.java, src/main/java/ceos/backend/global/config/jwt/TokenProvider.java, src/main/resources/application.yml
---
레디스를 이용해 리프레시 토큰 관련 로직을 구현했습니다.
- 로그인 로직 수정 : 로그인 시 레디스에 리프레시 토큰 등록
- 로그아웃 로직 수정 : 레디스에서 key 값을 통해 토큰 삭제
- 그 외 예외처리 : 액세스토큰으로 reissue 시도, 만료된 리프레시 토큰 관련 에러처리 추가
---
feat/refresh
---
이슈 번호
- close #66
=> [feat] 리프레시 토큰 구현

src/main/java/ceos/backend/domain/application/domain/Application.java, src/main/java/ceos/backend/domain/application/domain/ApplicationDetail.java, src/main/java/ceos/backend/domain/application/dto/request/CreateApplicationRequest.java, src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/domain/application/vo/InterviewDateTimesVo.java, src/main/java/ceos/backend/global/common/dto/AwsSESMail.java, src/main/java/ceos/backend/global/common/dto/mail/CeosQuestionInfo.java, src/main/java/ceos/backend/global/common/dto/mail/GreetInfo.java, src/main/java/ceos/backend/global/util/DurationFormatter.java, src/main/java/ceos/backend/global/util/ParsingDuration.java, src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java, src/main/java/ceos/backend/infra/ses/AwsSESSendMailHandler.java
---
application question response 변경
---
---
이슈 번호
- close #77
=> [feat] application question response 변경

src/main/java/ceos/backend/domain/application/dto/request/UpdateApplicationQuestion.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/domain/application/vo/ApplicationBriefInfoVo.java
---
application 질문 관련 response 변경 
---
---
이슈 번호
- close #86
=> [feat] application 질문 관련 response 변경

src/main/java/ceos/backend/domain/application/ApplicationController.java, src/main/java/ceos/backend/domain/application/enums/SortType.java, src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java
---
application 전체보기 sorting 추가
---
=> [feat] application 전체보기 sorting 추가

src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
---
에러 처리 조건 추가 
---
fix/application
---
이슈 번호
- close #89
=> [fix] 에러 처리 조건 추가 

src/main/java/ceos/backend/domain/recruitment/service/RecruitmentService.java
---
리크루팅 정보 수정 제한 제거
---
refact/recruitments
---
이슈 번호
- close #
=> [refact] 리크루팅 정보 수정 제한 제거

src/main/java/ceos/backend/domain/application/enums/SortType.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java
---
지원서 전체 불러오기 sorting type 추가
---
refac/application
=> [refact] 지원서 전체 불러오기 sorting type 추가

src/main/java/ceos/backend/domain/application/ApplicationController.java, src/main/java/ceos/backend/domain/application/enums/SortPartType.java, src/main/java/ceos/backend/domain/application/enums/SortPassType.java, src/main/java/ceos/backend/domain/application/enums/SortType.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java
---
파트, 서류합, 최종합 3가지로 정렬 방식 변경
---
=> [refact] application 전체 보기 정렬 분리

src/main/java/ceos/backend/domain/activity/dto/GetAllActivitiesResponse.java, src/main/java/ceos/backend/domain/application/dto/response/GetApplications.java, src/main/java/ceos/backend/domain/awards/dto/response/AllAwardsResponse.java, src/main/java/ceos/backend/domain/awards/dto/response/AwardsResponse.java, src/main/java/ceos/backend/domain/awards/service/AwardsService.java, src/main/java/ceos/backend/domain/management/ManagementController.java, src/main/java/ceos/backend/domain/management/dto/response/GetAllManagementsResponse.java, src/main/java/ceos/backend/domain/project/dto/response/GetProjectsResponse.java, src/main/java/ceos/backend/domain/sponsor/dto/response/GetAllSponsorsResponse.java
---
- 모든 페이징 필드명 content로 통일했습니다
- award response에 id 추가
- award paging index 관련 버그(객체 수보다 페이지 인덱스가 큰 경우) 고쳤습니다
- management api url mangement에서 management로 수정했습니다
---
refact/paging
---
이슈 번호
- close #
=> [refact] 페이징 필드명 content로 통일

src/main/java/ceos/backend/domain/application/dto/request/UpdateInterviewTime.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/global/common/dto/ParsedDuration.java, src/main/java/ceos/backend/global/util/ParsingDuration.java, src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
---
인터뷰 시간 정하기 request 변경
---
refact/application
---
이슈 번호
- #97
=> [refact] 인터뷰 시간 정하기 request 변경

src/main/java/ceos/backend/domain/awards/AwardsController.java, src/main/java/ceos/backend/domain/awards/service/AwardsService.java
---
기수별 수상이력 전체삭제 api를 추가합니다
---
add/awards
---
이슈 번호
- close #
=> [add] 기수별 수상이력 전체삭제

src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/vo/ApplicationBriefInfoVo.java, src/main/java/ceos/backend/global/common/dto/ParsedDuration.java
---
application 전체보기 response 변경
---
---
=> [refac] application 전체보기 response 변경

.github/workflows/deploy.yml, src/main/java/ceos/backend/domain/application/domain/Pass.java, src/test/java/ceos/backend/domain/application/ApplicationControllerTest.java, src/test/java/ceos/backend/domain/application/ApplicationExcelServiceTest.java
---
Github Action 에서 Gradle build spotlessApply 로 변경했습니다.
---
fix/spotless
---
이슈 번호
- close #108
=> [fix] Gradle build spotless 에러 

src/main/java/ceos/backend/domain/sponsor/SponsorController.java, src/main/java/ceos/backend/domain/sponsor/service/SponsorService.java
---
Sponsor 하나 조회 api 구현
---
feat/sponsor
---
이슈 번호
- close #110
=> [feat] sponsor 하나 조회 api 구현 

src/main/java/ceos/backend/domain/project/ProjectController.java, src/main/java/ceos/backend/domain/project/exception/ProjectErrorCode.java, src/main/java/ceos/backend/domain/project/exception/ProjectNotFound.java
---
- 프로젝트 수정 API 리팩토링 수행 - queryParameter -> pathVariable
- 에러코드 정리
---
feat/project
---
이슈 번호
- close #112
=> [refact] Project 리팩토링

src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java
---
결과 확인 response 변경
---
refact/application
---
=> [refact] 결과 확인 response 변경

src/main/java/ceos/backend/domain/admin/AdminController.java, src/main/java/ceos/backend/domain/admin/dto/response/GetAdminsResponse.java, src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java, src/main/java/ceos/backend/domain/admin/repository/AdminMapper.java, src/main/java/ceos/backend/domain/admin/repository/AdminRepository.java, src/main/java/ceos/backend/domain/admin/service/AdminService.java, src/main/java/ceos/backend/domain/admin/vo/AdminBriefInfoVo.java
---
- 누락된 어노테이션 적용
- 응답에 Part 필드 추가
- 페이징 적용
---
feat/project
---
이슈 번호
- close #115
=> [refact] Admin 리팩토링

src/main/java/ceos/backend/domain/application/domain/ApplicantInfo.java, src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
application security 수정
---
refact/application
---
=> [refact] application security 수정

src/main/java/ceos/backend/domain/admin/AdminController.java, src/main/java/ceos/backend/domain/admin/dto/request/RefreshTokenRequest.java, src/main/java/ceos/backend/domain/admin/service/AdminService.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
/reissue API에 토큰 적용을 해제하고 토큰 재발급 로직을 수정했습니다.
---
feat/admin
---
이슈 번호
- close #118
=> [fix] 토큰 재발급 로직 수정

src/main/java/ceos/backend/domain/application/domain/ApplicantInfo.java, src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java
---
합격 조회 response 수정
---
refact/application
---
=> [refact] 합격 조회 response 수정

src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java, src/main/java/ceos/backend/domain/application/exception/NotSetInterviewTime.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java
---
서류 결과 확인하기 기능 면접 시간 확정 여부 validation 추가
---
fix/application
---
이슈 번호
- close #121
=> [feat] 서류 결과 확인하기 기능 500 해결

src/main/java/ceos/backend/domain/project/repository/ProjectRepository.java, src/main/java/ceos/backend/domain/project/service/ProjectService.java
---
프로젝트를 역순서로 변경했습니다.
---
feat/project
---
이슈 번호
- close #124
=> [refact] 프로젝트 순서 변경

src/main/java/ceos/backend/domain/application/domain/ApplicationQuestion.java
---
application question 가져오기 response 변경
---
fix/application
---
=> [fix] application question 가져오기 response 변경

src/main/java/ceos/backend/domain/project/helper/ProjectHelper.java, src/main/java/ceos/backend/domain/project/repository/ProjectMapper.java, src/main/java/ceos/backend/domain/project/service/ProjectService.java, src/main/java/ceos/backend/domain/project/vo/ParticipantVo.java
---
- 팀원명에 null 값 허용
- 사용하지 않는 validation 삭제
---
feat/project
---
이슈 번호
- close #127
=> [refact] 프로젝트 생성 API 변경

src/main/java/ceos/backend/domain/project/helper/ProjectHelper.java, src/main/java/ceos/backend/domain/project/repository/ProjectMapper.java, src/main/java/ceos/backend/domain/project/service/ProjectService.java, src/main/java/ceos/backend/domain/project/vo/ParticipantVo.java
---
- 팀원명에 null 값 허용 -> DB에도 저장하도록 수정했습니다.
---
feat/project
---
이슈 번호
- close #127
=> [refact] 프로젝트 생성 API 수정

src/main/java/ceos/backend/domain/application/domain/ApplicationQuestion.java, src/main/java/ceos/backend/domain/application/domain/QuestionCategory.java, src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java, src/main/java/ceos/backend/domain/application/exception/NotSetInterviewTime.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java
---
save query 순서 변경 및 enum value 변경
---
fix/application
---
이슈 번호
- close #131
=> [fix] 지원하기 hibernate 500 에러 해결

src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
---
지원서 질문 보기 API 에서 면접 시간에 정렬 기능을 추가했습니다
---
refactor/interviewtime-sort
---
이슈 번호
- close #138
=> [refactor] 면접 시간 정렬 추가

src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java, src/main/java/ceos/backend/domain/admin/service/AdminService.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java, src/main/java/ceos/backend/global/config/jwt/JwtAccessDeniedHandler.java, src/main/java/ceos/backend/global/error/exception/ForbiddenAdmin.java
---
임시 권한을 가진 어드민은 로그인을 차단하는 코드를 추가했습니다.
---
feat/admin
---
이슈 번호
- close #140
=> [add] 임시어드민 로그인 차단

src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
origin 허용 임시 추가
---
refact/url
---
이슈 번호
- close #142
=> [refact] origin 허용 임시 추가

src/main/java/ceos/backend/domain/project/repository/ProjectMapper.java, src/main/java/ceos/backend/domain/project/repository/ProjectRepository.java, src/main/java/ceos/backend/domain/project/service/ProjectService.java, src/main/java/ceos/backend/domain/project/vo/ProjectImageVo.java
---
- 정렬 아이디 내림차순 -> 기수 내림차순
- 썸네일 없는 경우 필터링 (디비에 이미지 없는 경우도 필요함)
- 이미지 필수 해제
---
refact/projects
---
이슈 번호
- close #144
=> [refact] 프로젝트 페이지 정렬 수정, 프로젝트 이미지 관련 수정

.github/CODEOWNERS, .github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml, config/nginx/default.conf, docker-compose.dev.yml
---
개발, 운영 서버 분리
---
dev
---
이슈 번호
- close #148
=> [refact] 개발, 운영 서버 분리

build.gradle, src/main/java/ceos/backend/domain/application/ApplicationController.java, src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java, src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java, src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java, src/main/java/ceos/backend/domain/application/repository/ApplicationRepositoryCustom.java, src/main/java/ceos/backend/domain/application/repository/ApplicationRepositoryCustomImpl.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java, src/main/java/ceos/backend/global/common/entity/Part.java
* 이전의 검색 쿼리를 QueryDsl로 수정하였음
---
application_query
* 이전의 쿼리는 나중에 검색어가 추가되면 코드 유지보수가 힘들 수도 있었으나 QueryDsl을 사용함으로써 이 점을 개선
* 또한 All과 같은 값을 없에고 안쓰는 검색 조건은 쿼리에 값을 넣지 않아도 되서 직관성을 높임
=> [feat] 이름으로 이력서 검색 기능 추가

.github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml, .gitignore, docker-compose.dev.yml, docker-compose.yml, src/main/java/ceos/backend/domain/application/repository/ApplicationRepositoryCustomImpl.java, src/main/java/ceos/backend/global/common/entity/Part.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
- close #
=> Security deploy

src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
작업 사항
프론트 dev url을 코드에 추가해서 CORS에러를 막고자 하였습니다.
---
작업 브랜치
---
이슈 번호
- close #
=> feat : front dev url 추가

src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java, src/main/java/ceos/backend/domain/recruitment/dto/RecruitmentDTO.java, src/main/java/ceos/backend/domain/recruitment/dto/UserRecruitmentDTO.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java
---
recruitment response에 아이디어톤, 해커톤 날짜를 추가합니다
---
add/recruitment
---
이슈 번호
- close #
=> [add] 아이디어톤, 해커톤 날짜 추가

src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java, src/main/java/ceos/backend/domain/application/vo/ApplicantInfoVo.java, src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java, src/main/java/ceos/backend/domain/recruitment/dto/RecruitmentDTO.java, src/main/java/ceos/backend/domain/recruitment/dto/UserRecruitmentDTO.java, src/main/java/ceos/backend/domain/recruitment/validator/RecruitmentValidator.java, src/test/java/ceos/backend/domain/recruitments/domain/SettingsTest.java
---
1. LocalDate -> LocalDateTime
2. 서류합격공지 validation 수정
3. Positive -> PositiveorZero
---
refact/recruit
---
이슈 번호
- close #158
=> [refact] 홈페이지 수정사항 반영

.github/workflows/deploy_dev.yml, src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java, src/main/java/ceos/backend/domain/application/vo/ApplicantInfoVo.java, src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java, src/main/java/ceos/backend/domain/recruitment/dto/RecruitmentDTO.java, src/main/java/ceos/backend/domain/recruitment/dto/UserRecruitmentDTO.java, src/main/java/ceos/backend/domain/recruitment/validator/RecruitmentValidator.java, src/main/java/ceos/backend/global/config/WebSecurityConfig.java, src/test/java/ceos/backend/domain/recruitments/domain/SettingsTest.java
---
워크플로우 수정 및 프로비저닝
---
refact/os-migration
---
이슈 번호
- close #161
=> [refact] os migration

.github/workflows/deploy_dev.yml, .github/workflows/deploy_prod.yml, config/nginx/Dockerfile, docker-compose.dev.yml
---
- nginx 기존 방법에서 이미지 push 및 pull 해오는 방법으로 변경
- 트러블슈팅
---
refact/os-migration
---
이슈 번호
- close #161
=> [refact] linux os로 마이그레이션

docker-compose.yml
---
작업 사항
docker-compose.yml 수정
---
작업 브랜치
fix/docker-compose
---
이슈 번호
- close #171
=> [fix] docker-compose.yml 수정

.gitignore, src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java
---
이거 저번 기수 때, 에러 났던거임
불합격 결과 조회시, NPE 안터지게 수정했음
---
fix/application_response
=> [fix] 서류 결과 확인 response 생성 로직 수정

src/main/resources/templates/component/greeting.html, src/main/resources/templates/component/recruit.html, src/main/resources/templates/component/recruitGreeting.html, src/main/resources/templates/sendRecruitMail.html
---
이메일 등록한 subscriber에게 보낼 recruit email html 스타일 수정했습니다!
---
feat/emailhtml
=> [Feat] subscriber에게 보낼 recruit email html 수정

src/main/java/ceos/backend/domain/management/domain/ManagementPart.java, src/main/java/ceos/backend/domain/management/domain/ManagementRole.java, src/main/java/ceos/backend/domain/management/dto/response/GetAllPartManagementsResponse.java, src/main/java/ceos/backend/domain/management/mapper/ManagementMapper.java, src/main/java/ceos/backend/domain/management/service/ManagementService.java, src/main/java/ceos/backend/domain/management/vo/ManagementVo.java
---
managementPart, managementRole에 advisor(고문) 추가
`/managements/part` 에 advisors 반환 추가
---
작업 브랜치
---
이슈 번호
- close #197
=> feat: management part, role에 advisor 추가

src/main/java/ceos/backend/domain/management/domain/Management.java, src/main/java/ceos/backend/domain/management/domain/ManagementRole.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
- close #
=> chore: 주석 추가

src/main/resources/templates/component/copyright.html, src/main/resources/templates/component/title.html
---
메일에 들어가는 ceos logo 이미지를 s3에 추가한 후 image url 업데이트 하였습니다.
---
작업 브랜치
---
이슈 번호
- close #
=> [fix] ceos logo image update

src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java
---
서류 결과 반환하는 response dto에 part info 추가했습니다.
---
작업 브랜치
---
이슈 번호
- close #
=> [feat] GetResultResponse dto에 part info 추가

.github/workflows/deploy_prod.yml
---
1. docker-compose -> docker compose로 명령어 수정
2. env 파일 경로 수정
---
작업 브랜치
---
이슈 번호
- close #
=> [chore] docker compose 실행 명령어 수정

src/main/resources/application.yml
---
/swagger로 스웨거 접속이 가능하도록 경로 수정하였습니다
---
작업 브랜치
---
이슈 번호
- close #
=> environment: swagger path 수정

.github/workflows/deploy_dev.yml, src/main/java/ceos/backend/domain/project/s3
---
prod, dev에서 같은 APPLICATION_SECRET을 활용하도록 workflow 수정하였습니다.
---
작업 브랜치
---
이슈 번호
- close #
=> environment: workflow 수정 - prod, dev 공통 secret 활용

src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java, src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java, src/main/java/ceos/backend/domain/application/service/ApplicationService.java
---
작업 사항
---
작업 브랜치
---
이슈 번호
- close #
=> Feat: Application 락 적용

src/main/resources/application.yml
---
지원자 상태값 변동 이슈(합→불 자동 변경)를 추적하기 위해 Hibernate SQL 및 파라미터 바인딩 로그를 활성화함
---
main
=> chore: DB 로그 찍기

src/main/resources/application.yml
Reverts CEOS-Developers/CEOS-BE#219
=> Revert "chore: DB 로그 찍기"

src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java, src/main/java/ceos/backend/domain/recruitment/dto/RecruitmentDTO.java, src/main/java/ceos/backend/domain/recruitment/dto/UserRecruitmentDTO.java
---
1. Recruitment 테이블에 MT info 추가
2. 리크루팅 정보 보기 response DTO에 MT info 추가
3. 리크루팅 정보 수정 request DTO에 MT info 추가
---
작업 브랜치
---
이슈 번호
- close #
=> feat: recruitment - MT info 추가

src/main/resources/templates/component/greeting.html, src/main/resources/templates/component/recruit.html, src/main/resources/templates/component/recruitGreeting.html, src/main/resources/templates/component/title.html
---
22기에 맞게 메일 내용 수정했습니다.
---
작업 브랜치
---
이슈 번호
- close #
=> Chore: 22기 메일 내용 변경

src/main/resources/templates/component/recruit.html
---
리크루팅 시작 알림 메일에 면접 방식을 '온/오프라인'으로 수정
---
작업 브랜치
---
이슈 번호
- close #
=> chore: 지원 알림 메일 문구 수정
